import { applyMiddleware, combineReducers, compose, createStore } from "redux";
import stepsMiddleware from "redux-effects-steps";
import eventReducers from "store/ducks/events";
import axiosMiddleware from "store/middleware/axiosMiddleware";

// StoreにMiddlewareを追加する
const storeEnhancer = compose(applyMiddleware(...[stepsMiddleware, axiosMiddleware]));

// The reducer generated by combineReducers({ a, b }) looks like this:
// function combined(state = {}, action) {
//     return {
//       a: a(state.a, action),
//       b: b(state.b, action)
//     }
//   }
const allReducers = combineReducers({
  events: eventReducers,
});
// → storeに格納されるオブジェクトがこんな感じになる。
//
//    state = {
//        events: {
//            events: []
//            isLoading: false,
//            errorMessage: ""
//        }
//    }
//
//   reducerごとに定義した初期値が、それぞれのフィールドで管理される

// combineReducers使うときは argsのpreloadedStoreは空にする
// 参考: https://redux.js.org/usage/structuring-reducers/initializing-state
const store = createStore(allReducers, {}, storeEnhancer);

export default store;
